import { db } from "./db";
import { listings } from "@shared/schema";

const vancouverVenues = [
  {
    name: "Cactus Club Cafe - English Bay",
    type: "Restaurant Deal",
    city: "Vancouver",
    description: "Happy Hour 3-6PM: 25% off appetizers, cocktails, and wine. Oceanfront dining with spectacular views.",
    imageUrl: "https://images.unsplash.com/photo-1552566626-52f8b828add9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
    latitude: "49.2887",
    longitude: "-123.1366",
    validUntil: "2025-12-31",
    qrCode: "LIV-CACTUS-EB",
    website: "https://cactusclubcafe.com",
    phone: "(604) 681-2582",
    address: "1790 Beach Ave, Vancouver, BC V6G 1Y9",
    hours: "11:00 AM - 12:00 AM",
    tags: ["seafood", "cocktails", "patio", "view"],
    rating: "4.2",
    priceRange: "$$$",
    isActive: true,
  },
  {
    name: "The Commodore Ballroom",
    type: "Event",
    city: "Vancouver",
    description: "Live music venue hosting top artists. Check out upcoming concerts and special events.",
    imageUrl: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
    latitude: "49.2807",
    longitude: "-123.1207",
    validUntil: "2025-12-31",
    qrCode: "LIV-COMMODORE",
    website: "https://livenation.com",
    phone: "(604) 739-4550",
    address: "868 Granville St, Vancouver, BC V6Z 1K3",
    hours: "Varies by event",
    tags: ["live music", "concerts", "entertainment", "historic"],
    rating: "4.5",
    priceRange: "$$",
    isActive: true,
  },
  {
    name: "Science World",
    type: "Event",
    city: "Vancouver",
    description: "Interactive science exhibits and special events. Family-friendly educational entertainment.",
    imageUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
    latitude: "49.2734",
    longitude: "-123.1030",
    validUntil: "2025-12-31",
    qrCode: "LIV-SCIENCE",
    website: "https://scienceworld.ca",
    phone: "(604) 443-7440",
    address: "1455 Quebec St, Vancouver, BC V6A 3Z7",
    hours: "10:00 AM - 5:00 PM",
    tags: ["family", "education", "interactive", "science"],
    rating: "4.4",
    priceRange: "$$",
    isActive: true,
  },
  {
    name: "Granville Island Brewing",
    type: "Restaurant Deal",
    city: "Vancouver",
    description: "Craft brewery with tasting room. $5 off brewery tours and 20% off merchandise.",
    imageUrl: "https://images.unsplash.com/photo-1608270586620-248524c67de9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
    latitude: "49.2712",
    longitude: "-123.1347",
    validUntil: "2025-12-31",
    qrCode: "LIV-GRANVILLE-BREW",
    website: "https://gib.ca",
    phone: "(604) 687-2739",
    address: "1441 Cartwright St, Vancouver, BC V6H 3R7",
    hours: "11:00 AM - 10:00 PM",
    tags: ["craft beer", "brewery", "tours", "local"],
    rating: "4.3",
    priceRange: "$$",
    isActive: true,
  },
  {
    name: "Nordstrom Vancouver",
    type: "Retail Deal",
    city: "Vancouver",
    description: "Luxury department store. Get 15% off your purchase with exclusive Liv member discount.",
    imageUrl: "https://images.unsplash.com/photo-1555529902-f6e8a3ccabd8?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
    latitude: "49.2857",
    longitude: "-123.1167",
    validUntil: "2025-12-31",
    qrCode: "LIV-NORDSTROM-15",
    website: "https://nordstrom.ca",
    phone: "(604) 699-2100",
    address: "799 Robson St, Vancouver, BC V6Z 2E7",
    hours: "10:00 AM - 9:00 PM",
    tags: ["fashion", "luxury", "shopping", "department"],
    rating: "4.1",
    priceRange: "$$$$",
    isActive: true,
  },
  {
    name: "Aritzia - Robson Street",
    type: "Retail Deal",
    city: "Vancouver",
    description: "Canadian women's fashion retailer. 20% off regular priced items for new customers.",
    imageUrl: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
    latitude: "49.2848",
    longitude: "-123.1207",
    validUntil: "2025-12-31",
    qrCode: "LIV-ARITZIA-20",
    website: "https://aritzia.com",
    phone: "(604) 684-3251",
    address: "1110 Robson St, Vancouver, BC V6E 1B2",
    hours: "10:00 AM - 9:00 PM",
    tags: ["women's fashion", "canadian", "trendy", "designer"],
    rating: "4.0",
    priceRange: "$$$",
    isActive: true,
  },
  {
    name: "Tim Hortons - Granville",
    type: "Restaurant Deal",
    city: "Vancouver",
    description: "Canadian coffee chain. Buy one coffee, get one 50% off during morning hours (6-10 AM).",
    imageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
    latitude: "49.2847",
    longitude: "-123.1162",
    validUntil: "2025-12-31",
    qrCode: "LIV-TIMMIES-BOGO",
    website: "https://timhortons.ca",
    phone: "(604) 688-4770",
    address: "1025 Granville St, Vancouver, BC V6Z 1L4",
    hours: "5:00 AM - 11:00 PM",
    tags: ["coffee", "breakfast", "canadian", "quick"],
    rating: "3.8",
    priceRange: "$",
    isActive: true,
  },
  {
    name: "Queen Elizabeth Theatre",
    type: "Event",
    city: "Vancouver",
    description: "Premier performing arts venue. Upcoming shows include musicals, ballet, and opera performances.",
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
    latitude: "49.2828",
    longitude: "-123.1143",
    validUntil: "2025-12-31",
    qrCode: "LIV-QET-SHOWS",
    website: "https://queenstheatre.ca",
    phone: "(604) 665-3050",
    address: "630 Hamilton St, Vancouver, BC V6B 5N6",
    hours: "Varies by show",
    tags: ["theatre", "performing arts", "musicals", "cultural"],
    rating: "4.6",
    priceRange: "$$$",
    isActive: true,
  },
  {
    name: "Lululemon - Robson",
    type: "Retail Deal",
    city: "Vancouver",
    description: "Premium athletic wear. 15% off for first-time Liv users plus free hemming service.",
    imageUrl: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
    latitude: "49.2843",
    longitude: "-123.1189",
    validUntil: "2025-12-31",
    qrCode: "LIV-LULU-15",
    website: "https://lululemon.com",
    phone: "(604) 681-3118",
    address: "970 Robson St, Vancouver, BC V6Z 1B7",
    hours: "10:00 AM - 9:00 PM",
    tags: ["athletic wear", "yoga", "premium", "canadian"],
    rating: "4.4",
    priceRange: "$$$$",
    isActive: true,
  },
  {
    name: "Whistler Village Gondola",
    type: "Event",
    city: "Whistler",
    description: "Scenic gondola rides with mountain views. Special winter and summer activities available.",
    imageUrl: "https://images.unsplash.com/photo-1551524164-6cf96ac93ea4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
    latitude: "50.1163",
    longitude: "-122.9574",
    validUntil: "2025-12-31",
    qrCode: "LIV-WHISTLER-GONDOLA",
    website: "https://whistler.com",
    phone: "(604) 967-8950",
    address: "4545 Blackcomb Way, Whistler, BC V8E 0X9",
    hours: "8:00 AM - 4:00 PM",
    tags: ["scenic", "outdoor", "mountains", "adventure"],
    rating: "4.7",
    priceRange: "$$$",
    isActive: true,
  }
];

export async function seedDatabase() {
  console.log("Seeding database with Vancouver venues...");
  
  try {
    // Clear existing data
    await db.delete(listings);
    
    // Insert new data
    await db.insert(listings).values(vancouverVenues);
    
    console.log(`Successfully seeded ${vancouverVenues.length} venues`);
  } catch (error) {
    console.error("Error seeding database:", error);
    throw error;
  }
}